### ISSUE TITLE
Write django plugin

### ISSUE THREAD

**Issue by sayanarijit** [sayanarijit/htmldoom#5]
Write django plugin

**Comment by Bhupesh-V** [comment]
Hey can you explain a bit more about this
Are you talking about **reusable apps** in Django

**Comment by sayanarijit** [comment]
Hi Bhupesh,

Thanks for your interest in this project. Sorry I have not defined the goal clearly.

SO here it is:

Django uses it's own HTML templating engine that renders data into HTML. However it is replaceable with other templating engines like Jinja2.

The aim here is to design a plugin for Django that will allow Django users to use htmldoom as the view renderer and is easy to integrate with Django (like the Jinja2 integration).

**Comment by sayanarijit** [comment]
I guess I need to better document it first. I was hoping to find contributors for that.

**Comment by sayanarijit** [comment]
@Bhupesh-V Sorry I had to make some big changes to make it performant and improve the syntax. Let me know if you are still interested. I have already made a [plugin for Pyramid](https://github.com/sayanarijit/pyramid_htmldoom) that imports the `render` function from a given template and executes it with the given data. You may refer to the implementation.

**Comment by sayanarijit** [comment]
FYI Flask plugin: https://github.com/sayanarijit/flask-htmldoom

**Comment by sayanarijit** [comment]
I gave it a shot. And it seems it will take more than a day (probably weekend) which I cannot afford right now. Even if I create and publish it, managing it will take more effort as I don't use Django primarily.
I'll leave it to the success of other plugins and the Django community.
